// Generated by CoffeeScript 1.7.1
(function() {
  var app, request, should;

  request = require('supertest');

  should = require('should');

  app = require('../lib/app');

  describe('App', function() {
    it('Should do something', function(done) {
      app.should.be["instanceof"](Function);
      app.init.should.be["instanceof"](Function);
      return done();
    });
    return it('Should answer on GET /', function(done) {
      return request(app).get('/').end(function(err) {
        return done(err);
      });
    });
  });

}).call(this);
