// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, index, util;

  express = require('express');

  app = express();

  module.exports = app;

  app.cache = {};

  util = require('util');

  index = require('./routes/index');

  app.init = function(port) {
    if (port == null) {
      port = 1234;
    }
    console.log(util.format('App started. Listening on %d', port));
    return app.listen(port);
  };

  app.use(app.router);

  app.use(express["static"](__dirname + '/../static/dartangular/web'));

  app.use(express["static"](__dirname + '/../static/dartangular/build/web'));

  app.get('/api/user/:user', index.user);

  app.get('/', index.index);

}).call(this);
