// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, index, util;

  express = require('express');

  app = express();

  module.exports = app;

  app.cache = {};

  util = require('util');

  index = require('./routes/index');

  app.init = function(ip, port) {
    if (ip == null) {
      ip = '127.0.0.1';
    }
    if (port == null) {
      port = 8080;
    }
    console.log(util.format('App started. Listening on %d', port));
    return app.listen(port, ip);
  };

  app.use(app.router);

  app.use(express["static"](__dirname + '/../static/dartangular/web'));

  app.use(express["static"](__dirname + '/../static/dartangular/build/web'));

  app.get('/api/userstatus/:user', index.user);

  app.get('/api/user', index.allusers);

  app.get('/', index.index);

}).call(this);
