// Generated by CoffeeScript 1.7.1
(function() {
  var app, config, octo, settings;

  octo = require('tripping-octo-nemesis');

  config = require('yaml-config');

  app = require('../app');

  settings = config.readConfig('./config.yml');

  module.exports = {
    user: function(req, res) {
      var user, _ref, _ref1;
      user = req.params.user;
      if (!settings[user]) {
        res.send(404);
        return;
      }
      if (((_ref = app.cache[user]) != null ? (_ref1 = _ref.updated) != null ? _ref1.getTime() : void 0 : void 0) < (new Date().getTime() + 60000)) {
        res.send(app.cache[user]);
        return;
      }
      return octo.init(settings[user], false, function(err, _) {
        return octo.status(function(err, result) {
          var data;
          if (!err) {
            data = {
              status: result,
              updated: new Date()
            };
            app.cache[user] = data;
            res.send(data);
            return;
          }
          return res.send(500, 'problems');
        });
      });
    },
    index: function(req, res) {
      return res.sendfile("static/dartangular/web/index.html");
    }
  };

}).call(this);
