name: dartangular
description: A sample web application
dependencies:
  angular: any
  browser: any
  web_components: any
  shadow_dom: any

transformers:
- angular:
    html_files:
      - web/book-ctrl.html
- $dart2js: 
    {'minify':true}